data_dir: "/DATASERVER/MIC/SHARED/NYU_FastMRI/Preprocessed/multicoil_train/"
save_dir: "/DATASERVER/MIC/GENERAL/STUDENTS/aslock2/Preprocessed_CS/multicoil_train/"
mat_dir: '/DATASERVER/MIC/GENERAL/STUDENTS/aslock2/fastMRI-hybrid-modelling/fastMRI/sampling_profiles_CS.mat'
workers: 30
amount_training_files: 1000